import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-gray-800 text-white">
        <nav className="flex items-center justify-between py-4">
          <img src="logo.png" alt="Logo" className="h-8" />
          <div className="flex">
            <a href="/" className="mx-4 hover:text-gray-400">
              Home
            </a>
            <a href="/events" className="mx-4 hover:text-gray-400">
              Events
            </a>
            <a href="/about-us" className="mx-4 hover:text-gray-400">
              About Us
            </a>
          </div>
        </nav>
      </header>

      <main className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <div className="flex flex-wrap justify-center">
          <a href="/events/ottawa" className="w-full sm:w-1/2 md:w-1/3 p-4">
            <div className="bg-white rounded-lg shadow-lg overflow-hidden">
              <img
                src="/ottawa.jpg"
                alt="Events in Ottawa"
                className="w-full h-48 object-cover"
              />
              <div className="p-4">
                <h2 className="text-lg font-semibold mb-2">Events in Ottawa</h2>
                <p className="text-gray-600 leading-relaxed">
                  Looking for exciting events in Ottawa? Look no further! Our
                  event app showcases a variety of events happening in Ottawa,
                  including music concerts, art exhibitions, and food festivals.
                  With something for everyone, you're sure to find an event that
                  suits your interests. Don't miss out on the fun, explore our
                  Ottawa events today.
                </p>
              </div>
            </div>
          </a>
          <a
            href="/events/saskatchewan"
            className="w-full sm:w-1/2 md:w-1/3 p-4"
          >
            <div className="bg-white rounded-lg shadow-lg overflow-hidden">
              <img
                src="/saskatchewan.jpg"
                alt="Events in Saskatchewan"
                className="w-full h-48 object-cover"
              />
              <div className="p-4">
                <h2 className="text-lg font-semibold mb-2">
                  Events in Saskatchewan
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  Saskatchewan may be known for its flat terrain, but our event
                  app shows that the province is anything but boring. From music
                  festivals to agricultural fairs, Saskatchewan has plenty of
                  exciting events to explore. Browse our selection of events in
                  Saskatchewan to find something that sparks your interest.
                </p>
              </div>
            </div>
          </a>
          <a href="/events/vancouver" className="w-full sm:w-1/2 md:w-1/3 p-4">
            <div className="bg-white rounded-lg shadow-lg overflow-hidden">
              <img
                src="/vancouver.jpg"
                alt="Events in Vancouver"
                className="w-full h-48 object-cover"
              />
              <div className="p-4">
                <h2 className="text-lg font-semibold mb-2">
                  Events in Vancouver
                </h2>
                <p className="text-gray-600 leading-relaxed">
                  Vancouver is a bustling city that is home to a diverse range
                  of events throughout the year. Whether you're looking for a
                  food festival, a music concert, or a cultural celebration,
                  Vancouver has something to offer. Our event app makes it easy
                  to stay up-to-date on the latest events in Vancouver. Start
                  exploring today!
                </p>
              </div>
            </div>
          </a>
        </div>

        <div>
          <h2></h2>
        </div>
      </main>

      <footer className="bg-gray-800 text-white py-4 my-">
        <p className="text-center">&copy; 2023 Proudly Made in Ottawa 🇨🇦</p>
      </footer>
    </div>
  );
}
